Use id to identify list
gridsuite/actions-server pull request #21
Opened 2021-06-30 08:48 UTC by JacquesBorsenberger

2021-07-01 13:25 UTC, niconoir requested changes
It is possible to create contingency lists without specifying their ids in the creation request. The ids are then created when inserting the contingency list in the database. It might then be useful to return the newly created object value in the response body in order for the client to know what is the id of the newly created contingency list. Furthermore, with this behaviour, the PUT request used for contingency list creation is no more idempotent. Wouldn't it be better to change the PUT request to a POST request and return the newly created object (or updated object) in response body ?

2021-07-01 13:25 UTC, niconoir commented on src/main/resources/actions.sql
> +    create table filters_contingency_list (
Table filters_contingency_list is already created before. In fact, all tables creations and indexes creations are duplicated  !

2021-07-01 15:07 UTC, JacquesBorsenberger commented on src/main/java/org/gridsuite/actions/server/ContingencyListController.java
> +    @GetMapping(value = "metadata", produces = MediaType.APPLICATION_JSON_VALUE)
trying to be a bit generic to address different servers with the same request (like filter-server )

2021-07-02 11:56 UTC, niconoir approved these changes

2021-07-02 13:08 UTC, merged